# Generated by Django 4.0.3 on 2022-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='smtp_receiver',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='smtp_sender',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='smtp_subject',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
