# Generated by Django 4.0.3 on 2022-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_networkconndescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_uri', models.CharField(default=None, max_length=100)),
                ('smtp_port', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
