# Generated by Django 4.0.3 on 2022-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_config_smtp_receiver_config_smtp_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='smtp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
