# Generated by Django 4.0.3 on 2022-07-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_config_smtp_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconndescription',
            name='code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
