# Generated by Django 4.0.3 on 2022-07-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_networkconndescription_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconndescription',
            name='code',
            field=models.IntegerField(default=None),
        ),
    ]
