# Generated by Django 4.0.3 on 2022-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('dns', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Up'), (1, 'Failed')], default=1)),
            ],
        ),
    ]
