# Generated by Django 4.0.3 on 2022-07-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=None)),
                ('status', models.IntegerField(choices=[(1, 'Up'), (0, 'Failed')], default=0)),
                ('error_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error_code', to='common.networkconndescription')),
            ],
        ),
    ]
