# Generated by Django 4.0.3 on 2022-07-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_networkconndescription'),
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='ip',
        ),
        migrations.AddField(
            model_name='watcher',
            name='error_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error_code', to='common.networkconndescription'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='status',
            field=models.IntegerField(choices=[(1, 'Up'), (0, 'Failed')], default=0),
        ),
    ]
