# Generated by Django 4.0.3 on 2022-07-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_remove_watcher_ip_watcher_error_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='port',
            field=models.IntegerField(default=None),
        ),
    ]
