# Generated by Django 4.0.3 on 2022-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact form message',
                'verbose_name_plural': 'contact form messages',
                'db_table': 'contactform',
            },
        ),
    ]
