# Generated by Django 4.0.3 on 2022-05-15 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='SubnetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_ip', models.GenericIPAddressField()),
                ('mask', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(0)])),
                ('cidr', models.CharField(max_length=40)),
            ],
        ),
    ]
