# Generated by Django 4.0.3 on 2022-05-15 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_mymodel_subnetform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('dns', models.CharField(max_length=100, null=True)),
                ('flag', models.CharField(choices=[('0', 'Reserved'), ('1', 'Non Reserved'), ('2', 'New One')], default='2', max_length=1)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_ip', models.GenericIPAddressField()),
                ('mask', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(0)])),
                ('cidr', models.CharField(default='None', editable=False, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='SubnetForm',
        ),
        migrations.AddField(
            model_name='ip',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.subnet'),
        ),
    ]
