# Generated by Django 4.0.3 on 2022-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_ip_subnet_delete_contactform_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NMAPTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('took_time_in_minute', models.IntegerField(default=0)),
                ('flag', models.CharField(choices=[('0', 'Finished'), ('1', 'Running'), ('2', 'Failed'), ('3', 'Not Started')], default='3', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='ip',
            name='flag',
        ),
    ]
