# Generated by Django 4.0.3 on 2022-05-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_nmaptask_remove_ip_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='subnet',
        ),
        migrations.DeleteModel(
            name='NMAPTask',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.DeleteModel(
            name='Subnet',
        ),
    ]
