# Generated by Django 4.0.3 on 2022-05-22 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(0)])),
                ('port_alias', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='port',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.PROTECT, related_name='port', to='subnet.port'),
        ),
    ]
