# Generated by Django 4.0.3 on 2022-06-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('subnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='description',
        ),
        migrations.AddField(
            model_name='ip',
            name='description',
            field=models.ManyToManyField(blank=True, null=True, to='common.description'),
        ),
    ]
