# Generated by Django 4.0.3 on 2022-05-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0002_port_ip_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_name', models.CharField(max_length=100)),
                ('regex', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ip',
            name='port',
        ),
        migrations.AddField(
            model_name='ip',
            name='port',
            field=models.ManyToManyField(to='subnet.port'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='desc', to='subnet.description'),
        ),
    ]
