# Generated by Django 4.0.3 on 2022-06-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('subnet', '0002_remove_ip_description_ip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='description',
            field=models.ManyToManyField(blank=True, to='common.description'),
        ),
    ]
