# Generated by Django 4.0.3 on 2022-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('subnet', '0003_alter_ip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='description',
            field=models.ManyToManyField(blank=True, null=True, to='common.description'),
        ),
    ]
