# Generated by Django 4.0.3 on 2022-05-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0003_description_remove_ip_port_ip_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desc', to='subnet.description'),
        ),
    ]
