# Generated by Django 4.0.3 on 2022-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0004_alter_ip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='port',
        ),
        migrations.AddField(
            model_name='ip',
            name='port',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
