# Generated by Django 4.0.3 on 2022-06-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('subnet', '0004_alter_ip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='description',
            field=models.ManyToManyField(blank=True, to='common.description'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subnet.subnet'),
        ),
    ]
