# Generated by Django 4.0.3 on 2022-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0005_alter_ip_description_alter_ip_subnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='subnet',
        ),
        migrations.AddField(
            model_name='ip',
            name='subnet',
            field=models.ManyToManyField(blank=True, null=True, to='subnet.subnet'),
        ),
    ]
